#!/bin/bash

# Script para generar transacciones.
# Ejemplo: ./genTransac -f genTransac.config.txt -n genTransac.nodo.txt -d logs/

# Parsear input
while [[ $# -gt 0 ]]; do
    key=$1

    case $key in
        -f)
            archivoConfig=$2
            shift
            shift
            ;;
        -n)
            archivoNodo=$2
            shift
            shift
            ;;
        -d)
            dirLogs=$2
            shift
            shift
            ;;
        *) # unknown option
            echo "Opcion invalida $key"
            exit 1
            ;;
    esac
done

if [[ -z $(command -v python) ]]; then
    echo "Please start a python environment to run the python command"
    exit 1
fi
python genTransac.py $archivoConfig $archivoNodo $dirLogs